language: php

php:
    - 7.2

before_script:
    - composer self-update
    - composer install --prefer-source --no-interaction --dev

script: phpunit --coverage-clover=coverage.xml

notifications:
    email: crystopher.glodzienski@gmail.com

cache:
    directories:
        - $HOME/.composer/cache/files

install:
    - composer install

#after_success:
#    - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN
