version: '3'
services:

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    volumes:
#      - "./.docker/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf"
#      - "./.docker/rabbitmq/rabbitmq.conf:/etc/rabbitmq/enabled_plugins"
      - "./.docker/rabbitmq/temp/data/:/var/lib/rabbitmq/"
      - "./.docker/rabbitmq/temp/logs/:/var/log/rabbitmq/"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "strong"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - net

  env:
    container_name: env
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ".:/var/www/package"
    networks:
      - net
    depends_on:
      - rabbitmq

networks:
  net:
    driver: bridge
